.TH radsecproxy-hash 1 "29 Sep 2011"

.SH "NAME"
radsecproxy-hash - print digests of Ethernet MAC addresses

.SH "SYNOPSIS"
.HP 12
radsecproxy-hash [\-h] [\-k key] [mac]...
.sp

.SH "DESCRIPTION"
Print the hash or hmac of Ethernet MAC addresses

.SH "OPTIONS"
.TP
.B \-h
\fIdisplay help and exit\fR

.TP
.B \-k key
\fIuse KEY for HMAC calculation\fR

.TP
.B mac
\fIMAC address to hash. Read from stdin if omitted.\fR


.SH "SEE ALSO"
radsecproxy.conf(5)
