.TH radsecproxy-hash 1 "5 May 2018"

.SH "NAME"
radsecproxy-hash - print digests of Ethernet MAC addresses

.SH "SYNOPSIS"
.HP 12
radsecproxy-hash [\-h] [\-k \fIKEY\fR] [\fIMAC\fR...]
.sp

.SH "DESCRIPTION"
Print the hash or hmac of Ethernet \fIMAC\fR addresses

.SH "OPTIONS"
.TP
.B \-h
Display help and exit

.TP
.B \-k \fIKEY\fR
.br
perform HMAC calculation using key \fIKEY\fR

.TP
With no \fIMAC\fR, read from standard input


.SH "SEE ALSO"
radsecproxy.conf(5)
