#!/sbin/runscript

depend() {
	use logger dns
	need net
}

CMD="/usr/sbin/radsecproxy"

start() {
	ebegin "Starting radsecproxy"
	if test -n "${OPTS}" ; then
		start-stop-daemon --start --exec ${CMD} -- ${OPTS} >/dev/null 2>&1
	else
		start-stop-daemon --start --exec ${CMD} -- >/dev/null 2>&1
	fi
	eend $?
}

stop() {
	ebegin "Stopping radsecproxy"
	start-stop-daemon --stop --exec ${CMD}
	eend $?
}
