/* Automatically generated file.  Do not edit */

#define VENDORPEC_MICROSOFT 311
#define VENDORPEC_EXAMPLE 65535


/* IETF */
#define PW_USER_NAME 1
#define PW_USER_PASSWORD 2
#define PW_CHAP_PASSWORD 3
#define PW_NAS_IP_ADDRESS 4
#define PW_NAS_PORT 5
#define PW_SERVICE_TYPE 6
#define PW_FRAMED_PROTOCOL 7
#define PW_FRAMED_IP_ADDRESS 8
#define PW_FRAMED_IP_NETMASK 9
#define PW_FRAMED_ROUTING 10
#define PW_FILTER_ID 11
#define PW_FRAMED_MTU 12
#define PW_FRAMED_COMPRESSION 13
#define PW_LOGIN_IP_HOST 14
#define PW_LOGIN_SERVICE 15
#define PW_LOGIN_TCP_PORT 16
#define PW_REPLY_MESSAGE 18
#define PW_CALLBACK_NUMBER 19
#define PW_CALLBACK_ID 20
#define PW_FRAMED_ROUTE 22
#define PW_FRAMED_IPX_NETWORK 23
#define PW_STATE 24
#define PW_CLASS 25
#define PW_VENDOR_SPECIFIC 26
#define PW_SESSION_TIMEOUT 27
#define PW_IDLE_TIMEOUT 28
#define PW_TERMINATION_ACTION 29
#define PW_CALLED_STATION_ID 30
#define PW_CALLING_STATION_ID 31
#define PW_NAS_IDENTIFIER 32
#define PW_PROXY_STATE 33
#define PW_LOGIN_LAT_SERVICE 34
#define PW_LOGIN_LAT_NODE 35
#define PW_LOGIN_LAT_GROUP 36
#define PW_FRAMED_APPLETALK_LINK 37
#define PW_FRAMED_APPLETALK_NETWORK 38
#define PW_FRAMED_APPLETALK_ZONE 39
#define PW_ACCT_STATUS_TYPE 40
#define PW_ACCT_DELAY_TIME 41
#define PW_ACCT_INPUT_OCTETS 42
#define PW_ACCT_OUTPUT_OCTETS 43
#define PW_ACCT_SESSION_ID 44
#define PW_ACCT_AUTHENTIC 45
#define PW_ACCT_SESSION_TIME 46
#define PW_ACCT_INPUT_PACKETS 47
#define PW_ACCT_OUTPUT_PACKETS 48
#define PW_ACCT_TERMINATE_CAUSE 49
#define PW_ACCT_MULTI_SESSION_ID 50
#define PW_ACCT_LINK_COUNT 51
#define PW_ACCT_INPUT_GIGAWORDS 52
#define PW_ACCT_OUTPUT_GIGAWORDS 53
#define PW_EVENT_TIMESTAMP 55
#define PW_EGRESS_VLANID 56
#define PW_INGRESS_FILTERS 57
#define PW_EGRESS_VLAN_NAME 58
#define PW_USER_PRIORITY_TABLE 59
#define PW_CHAP_CHALLENGE 60
#define PW_NAS_PORT_TYPE 61
#define PW_PORT_LIMIT 62
#define PW_LOGIN_LAT_PORT 63
#define PW_TUNNEL_TYPE 64
#define PW_TUNNEL_MEDIUM_TYPE 65
#define PW_TUNNEL_CLIENT_ENDPOINT 66
#define PW_TUNNEL_SERVER_ENDPOINT 67
#define PW_ACCT_TUNNEL_CONNECTION 68
#define PW_TUNNEL_PASSWORD 69
#define PW_ARAP_PASSWORD 70
#define PW_ARAP_FEATURES 71
#define PW_ARAP_ZONE_ACCESS 72
#define PW_ARAP_SECURITY 73
#define PW_ARAP_SECURITY_DATA 74
#define PW_PASSWORD_RETRY 75
#define PW_PROMPT 76
#define PW_CONNECT_INFO 77
#define PW_CONFIGURATION_TOKEN 78
#define PW_EAP_MESSAGE 79
#define PW_MESSAGE_AUTHENTICATOR 80
#define PW_TUNNEL_PRIVATE_GROUP_ID 81
#define PW_TUNNEL_ASSIGNMENT_ID 82
#define PW_TUNNEL_PREFERENCE 83
#define PW_ARAP_CHALLENGE_RESPONSE 84
#define PW_ACCT_INTERIM_INTERVAL 85
#define PW_ACCT_TUNNEL_PACKETS_LOST 86
#define PW_NAS_PORT_ID 87
#define PW_FRAMED_POOL 88
#define PW_CHARGEABLE_USER_IDENTITY 89
#define PW_TUNNEL_CLIENT_AUTH_ID 90
#define PW_TUNNEL_SERVER_AUTH_ID 91
#define PW_NAS_FILTER_RULE 92
#define PW_NAS_IPV6_ADDRESS 95
#define PW_FRAMED_INTERFACE_ID 96
#define PW_FRAMED_IPV6_PREFIX 97
#define PW_LOGIN_IPV6_HOST 98
#define PW_FRAMED_IPV6_ROUTE 99
#define PW_FRAMED_IPV6_POOL 100
#define PW_ERROR_CAUSE 101
#define PW_EAP_KEY_NAME 102
#define PW_DIGEST_RESPONSE 103
#define PW_DIGEST_REALM 104
#define PW_DIGEST_NONCE 105
#define PW_DIGEST_RESPONSE_AUTH 106
#define PW_DIGEST_NEXTNONCE 107
#define PW_DIGEST_METHOD 108
#define PW_DIGEST_URI 109
#define PW_DIGEST_QOP 110
#define PW_DIGEST_ALGORITHM 111
#define PW_DIGEST_ENTITY_BODY_HASH 112
#define PW_DIGEST_CNONCE 113
#define PW_DIGEST_NONCE_COUNT 114
#define PW_DIGEST_USERNAME 115
#define PW_DIGEST_OPAQUE 116
#define PW_DIGEST_AUTH_PARAM 117
#define PW_DIGEST_AKA_AUTS 118
#define PW_DIGEST_DOMAIN 119
#define PW_DIGEST_STALE 120
#define PW_DIGEST_HA1 121
#define PW_SIP_AOR 122
#define PW_DELEGATED_IPV6_PREFIX 123
#define PW_OPERATOR_NAME 126
#define PW_LOCATION_INFORMATION 127
#define PW_LOCATION_DATA 128
#define PW_BASIC_LOCATION_POLICY_RULES 129
#define PW_EXTENDED_LOCATION_POLICY_RULES 130
#define PW_LOCATION_CAPABLE 131
#define PW_REQUESTED_LOCATION_INFO 132
#define PW_FRAMED_MANAGEMENT 133
#define PW_MANAGEMENT_TRANSPORT_PROTECTION 134
#define PW_MANAGEMENT_POLICY_ID 135
#define PW_MANAGEMENT_PRIVILEGE_LEVEL 136
#define PW_PKM_SS_CERT 137
#define PW_PKM_CA_CERT 138
#define PW_PKM_CONFIG_SETTINGS 139
#define PW_PKM_CRYPTOSUITE_LIST 140
#define PW_PKM_SAID 141
#define PW_PKM_SA_DESCRIPTOR 142
#define PW_PKM_AUTH_KEY 143

/* Microsoft */
#define PW_MS_CHAP_RESPONSE 1
#define PW_MS_CHAP_ERROR 2
#define PW_MS_MPPE_ENCRYPTION_POLICY 7
#define PW_MS_MPPE_ENCRYPTION_TYPES 8
#define PW_MS_CHAP_DOMAIN 10
#define PW_MS_CHAP_CHALLENGE 11
#define PW_MS_CHAP_MPPE_KEYS 12
#define PW_MS_MPPE_SEND_KEY 16
#define PW_MS_MPPE_RECV_KEY 17
#define PW_MS_CHAP2_RESPONSE 25
#define PW_MS_CHAP2_SUCCESS 26

/* example */
#define PW_EXAMPLE_INTEGER 1
#define PW_EXAMPLE_STRING 2
#define PW_EXAMPLE_IP_ADDRESS 3

/* Fixed offsets to dictionary definitions of attributes */
#define NR_DA_USER_NAME (&nr_dict_attrs[1])
#define NR_DA_USER_PASSWORD (&nr_dict_attrs[2])
#define NR_DA_CHAP_PASSWORD (&nr_dict_attrs[3])
#define NR_DA_NAS_IP_ADDRESS (&nr_dict_attrs[4])
#define NR_DA_NAS_PORT (&nr_dict_attrs[5])
#define NR_DA_SERVICE_TYPE (&nr_dict_attrs[6])
#define NR_DA_FRAMED_PROTOCOL (&nr_dict_attrs[7])
#define NR_DA_FRAMED_IP_ADDRESS (&nr_dict_attrs[8])
#define NR_DA_FRAMED_IP_NETMASK (&nr_dict_attrs[9])
#define NR_DA_FRAMED_ROUTING (&nr_dict_attrs[10])
#define NR_DA_FILTER_ID (&nr_dict_attrs[11])
#define NR_DA_FRAMED_MTU (&nr_dict_attrs[12])
#define NR_DA_FRAMED_COMPRESSION (&nr_dict_attrs[13])
#define NR_DA_LOGIN_IP_HOST (&nr_dict_attrs[14])
#define NR_DA_LOGIN_SERVICE (&nr_dict_attrs[15])
#define NR_DA_LOGIN_TCP_PORT (&nr_dict_attrs[16])
#define NR_DA_REPLY_MESSAGE (&nr_dict_attrs[18])
#define NR_DA_CALLBACK_NUMBER (&nr_dict_attrs[19])
#define NR_DA_CALLBACK_ID (&nr_dict_attrs[20])
#define NR_DA_FRAMED_ROUTE (&nr_dict_attrs[22])
#define NR_DA_FRAMED_IPX_NETWORK (&nr_dict_attrs[23])
#define NR_DA_STATE (&nr_dict_attrs[24])
#define NR_DA_CLASS (&nr_dict_attrs[25])
#define NR_DA_VENDOR_SPECIFIC (&nr_dict_attrs[26])
#define NR_DA_SESSION_TIMEOUT (&nr_dict_attrs[27])
#define NR_DA_IDLE_TIMEOUT (&nr_dict_attrs[28])
#define NR_DA_TERMINATION_ACTION (&nr_dict_attrs[29])
#define NR_DA_CALLED_STATION_ID (&nr_dict_attrs[30])
#define NR_DA_CALLING_STATION_ID (&nr_dict_attrs[31])
#define NR_DA_NAS_IDENTIFIER (&nr_dict_attrs[32])
#define NR_DA_PROXY_STATE (&nr_dict_attrs[33])
#define NR_DA_LOGIN_LAT_SERVICE (&nr_dict_attrs[34])
#define NR_DA_LOGIN_LAT_NODE (&nr_dict_attrs[35])
#define NR_DA_LOGIN_LAT_GROUP (&nr_dict_attrs[36])
#define NR_DA_FRAMED_APPLETALK_LINK (&nr_dict_attrs[37])
#define NR_DA_FRAMED_APPLETALK_NETWORK (&nr_dict_attrs[38])
#define NR_DA_FRAMED_APPLETALK_ZONE (&nr_dict_attrs[39])
#define NR_DA_ACCT_STATUS_TYPE (&nr_dict_attrs[40])
#define NR_DA_ACCT_DELAY_TIME (&nr_dict_attrs[41])
#define NR_DA_ACCT_INPUT_OCTETS (&nr_dict_attrs[42])
#define NR_DA_ACCT_OUTPUT_OCTETS (&nr_dict_attrs[43])
#define NR_DA_ACCT_SESSION_ID (&nr_dict_attrs[44])
#define NR_DA_ACCT_AUTHENTIC (&nr_dict_attrs[45])
#define NR_DA_ACCT_SESSION_TIME (&nr_dict_attrs[46])
#define NR_DA_ACCT_INPUT_PACKETS (&nr_dict_attrs[47])
#define NR_DA_ACCT_OUTPUT_PACKETS (&nr_dict_attrs[48])
#define NR_DA_ACCT_TERMINATE_CAUSE (&nr_dict_attrs[49])
#define NR_DA_ACCT_MULTI_SESSION_ID (&nr_dict_attrs[50])
#define NR_DA_ACCT_LINK_COUNT (&nr_dict_attrs[51])
#define NR_DA_ACCT_INPUT_GIGAWORDS (&nr_dict_attrs[52])
#define NR_DA_ACCT_OUTPUT_GIGAWORDS (&nr_dict_attrs[53])
#define NR_DA_EVENT_TIMESTAMP (&nr_dict_attrs[55])
#define NR_DA_EGRESS_VLANID (&nr_dict_attrs[56])
#define NR_DA_INGRESS_FILTERS (&nr_dict_attrs[57])
#define NR_DA_EGRESS_VLAN_NAME (&nr_dict_attrs[58])
#define NR_DA_USER_PRIORITY_TABLE (&nr_dict_attrs[59])
#define NR_DA_CHAP_CHALLENGE (&nr_dict_attrs[60])
#define NR_DA_NAS_PORT_TYPE (&nr_dict_attrs[61])
#define NR_DA_PORT_LIMIT (&nr_dict_attrs[62])
#define NR_DA_LOGIN_LAT_PORT (&nr_dict_attrs[63])
#define NR_DA_TUNNEL_TYPE (&nr_dict_attrs[64])
#define NR_DA_TUNNEL_MEDIUM_TYPE (&nr_dict_attrs[65])
#define NR_DA_TUNNEL_CLIENT_ENDPOINT (&nr_dict_attrs[66])
#define NR_DA_TUNNEL_SERVER_ENDPOINT (&nr_dict_attrs[67])
#define NR_DA_ACCT_TUNNEL_CONNECTION (&nr_dict_attrs[68])
#define NR_DA_TUNNEL_PASSWORD (&nr_dict_attrs[69])
#define NR_DA_ARAP_PASSWORD (&nr_dict_attrs[70])
#define NR_DA_ARAP_FEATURES (&nr_dict_attrs[71])
#define NR_DA_ARAP_ZONE_ACCESS (&nr_dict_attrs[72])
#define NR_DA_ARAP_SECURITY (&nr_dict_attrs[73])
#define NR_DA_ARAP_SECURITY_DATA (&nr_dict_attrs[74])
#define NR_DA_PASSWORD_RETRY (&nr_dict_attrs[75])
#define NR_DA_PROMPT (&nr_dict_attrs[76])
#define NR_DA_CONNECT_INFO (&nr_dict_attrs[77])
#define NR_DA_CONFIGURATION_TOKEN (&nr_dict_attrs[78])
#define NR_DA_EAP_MESSAGE (&nr_dict_attrs[79])
#define NR_DA_MESSAGE_AUTHENTICATOR (&nr_dict_attrs[80])
#define NR_DA_TUNNEL_PRIVATE_GROUP_ID (&nr_dict_attrs[81])
#define NR_DA_TUNNEL_ASSIGNMENT_ID (&nr_dict_attrs[82])
#define NR_DA_TUNNEL_PREFERENCE (&nr_dict_attrs[83])
#define NR_DA_ARAP_CHALLENGE_RESPONSE (&nr_dict_attrs[84])
#define NR_DA_ACCT_INTERIM_INTERVAL (&nr_dict_attrs[85])
#define NR_DA_ACCT_TUNNEL_PACKETS_LOST (&nr_dict_attrs[86])
#define NR_DA_NAS_PORT_ID (&nr_dict_attrs[87])
#define NR_DA_FRAMED_POOL (&nr_dict_attrs[88])
#define NR_DA_CHARGEABLE_USER_IDENTITY (&nr_dict_attrs[89])
#define NR_DA_TUNNEL_CLIENT_AUTH_ID (&nr_dict_attrs[90])
#define NR_DA_TUNNEL_SERVER_AUTH_ID (&nr_dict_attrs[91])
#define NR_DA_NAS_FILTER_RULE (&nr_dict_attrs[92])
#define NR_DA_NAS_IPV6_ADDRESS (&nr_dict_attrs[95])
#define NR_DA_FRAMED_INTERFACE_ID (&nr_dict_attrs[96])
#define NR_DA_FRAMED_IPV6_PREFIX (&nr_dict_attrs[97])
#define NR_DA_LOGIN_IPV6_HOST (&nr_dict_attrs[98])
#define NR_DA_FRAMED_IPV6_ROUTE (&nr_dict_attrs[99])
#define NR_DA_FRAMED_IPV6_POOL (&nr_dict_attrs[100])
#define NR_DA_ERROR_CAUSE (&nr_dict_attrs[101])
#define NR_DA_EAP_KEY_NAME (&nr_dict_attrs[102])
#define NR_DA_DIGEST_RESPONSE (&nr_dict_attrs[103])
#define NR_DA_DIGEST_REALM (&nr_dict_attrs[104])
#define NR_DA_DIGEST_NONCE (&nr_dict_attrs[105])
#define NR_DA_DIGEST_RESPONSE_AUTH (&nr_dict_attrs[106])
#define NR_DA_DIGEST_NEXTNONCE (&nr_dict_attrs[107])
#define NR_DA_DIGEST_METHOD (&nr_dict_attrs[108])
#define NR_DA_DIGEST_URI (&nr_dict_attrs[109])
#define NR_DA_DIGEST_QOP (&nr_dict_attrs[110])
#define NR_DA_DIGEST_ALGORITHM (&nr_dict_attrs[111])
#define NR_DA_DIGEST_ENTITY_BODY_HASH (&nr_dict_attrs[112])
#define NR_DA_DIGEST_CNONCE (&nr_dict_attrs[113])
#define NR_DA_DIGEST_NONCE_COUNT (&nr_dict_attrs[114])
#define NR_DA_DIGEST_USERNAME (&nr_dict_attrs[115])
#define NR_DA_DIGEST_OPAQUE (&nr_dict_attrs[116])
#define NR_DA_DIGEST_AUTH_PARAM (&nr_dict_attrs[117])
#define NR_DA_DIGEST_AKA_AUTS (&nr_dict_attrs[118])
#define NR_DA_DIGEST_DOMAIN (&nr_dict_attrs[119])
#define NR_DA_DIGEST_STALE (&nr_dict_attrs[120])
#define NR_DA_DIGEST_HA1 (&nr_dict_attrs[121])
#define NR_DA_SIP_AOR (&nr_dict_attrs[122])
#define NR_DA_DELEGATED_IPV6_PREFIX (&nr_dict_attrs[123])
#define NR_DA_OPERATOR_NAME (&nr_dict_attrs[126])
#define NR_DA_LOCATION_INFORMATION (&nr_dict_attrs[127])
#define NR_DA_LOCATION_DATA (&nr_dict_attrs[128])
#define NR_DA_BASIC_LOCATION_POLICY_RULES (&nr_dict_attrs[129])
#define NR_DA_EXTENDED_LOCATION_POLICY_RULES (&nr_dict_attrs[130])
#define NR_DA_LOCATION_CAPABLE (&nr_dict_attrs[131])
#define NR_DA_REQUESTED_LOCATION_INFO (&nr_dict_attrs[132])
#define NR_DA_FRAMED_MANAGEMENT (&nr_dict_attrs[133])
#define NR_DA_MANAGEMENT_TRANSPORT_PROTECTION (&nr_dict_attrs[134])
#define NR_DA_MANAGEMENT_POLICY_ID (&nr_dict_attrs[135])
#define NR_DA_MANAGEMENT_PRIVILEGE_LEVEL (&nr_dict_attrs[136])
#define NR_DA_PKM_SS_CERT (&nr_dict_attrs[137])
#define NR_DA_PKM_CA_CERT (&nr_dict_attrs[138])
#define NR_DA_PKM_CONFIG_SETTINGS (&nr_dict_attrs[139])
#define NR_DA_PKM_CRYPTOSUITE_LIST (&nr_dict_attrs[140])
#define NR_DA_PKM_SAID (&nr_dict_attrs[141])
#define NR_DA_PKM_SA_DESCRIPTOR (&nr_dict_attrs[142])
#define NR_DA_PKM_AUTH_KEY (&nr_dict_attrs[143])
#define NR_DA_MS_CHAP_RESPONSE (&nr_dict_attrs[256])
#define NR_DA_MS_CHAP_ERROR (&nr_dict_attrs[257])
#define NR_DA_MS_MPPE_ENCRYPTION_POLICY (&nr_dict_attrs[258])
#define NR_DA_MS_MPPE_ENCRYPTION_TYPES (&nr_dict_attrs[259])
#define NR_DA_MS_CHAP_DOMAIN (&nr_dict_attrs[260])
#define NR_DA_MS_CHAP_CHALLENGE (&nr_dict_attrs[261])
#define NR_DA_MS_CHAP_MPPE_KEYS (&nr_dict_attrs[262])
#define NR_DA_MS_MPPE_SEND_KEY (&nr_dict_attrs[263])
#define NR_DA_MS_MPPE_RECV_KEY (&nr_dict_attrs[264])
#define NR_DA_MS_CHAP2_RESPONSE (&nr_dict_attrs[265])
#define NR_DA_MS_CHAP2_SUCCESS (&nr_dict_attrs[266])
#define NR_DA_EXAMPLE_INTEGER (&nr_dict_attrs[267])
#define NR_DA_EXAMPLE_STRING (&nr_dict_attrs[268])
#define NR_DA_EXAMPLE_IP_ADDRESS (&nr_dict_attrs[269])
/* Automatically generated file.  Do not edit */
